[project]
name = "rag"
version = "0.1.0"
description = "Getting started with RAG"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "collection>=0.1.6",
    "langchain>=1.2.6",
    "pykernel>=0.1.6",
]
